name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 13.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        npm install
        npm run build:prod --prod
        npm test
    - name: Upload Build folder
      uses: actions/upload-artifact@v1
      with:
        name: workday-manager-frontend
        path: /build/
        
        
      env:
        CI: true
